[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
btc_relay = "33tEfBs82iH2ZN26AP1quJnKB5vMaU7AgWRcDqank1ih"

[programs.mainnet]
btc_relay = "33tEfBs82iH2ZN26AP1quJnKB5vMaU7AgWRcDqank1ih"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "anchor.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
