[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
btc_relay = "3YS97dtVcWjXUnR8JrZUm1oACYdjhoNQEuMM7y7VdvTa"

[programs.mainnet]
btc_relay = "3YS97dtVcWjXUnR8JrZUm1oACYdjhoNQEuMM7y7VdvTa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "anchor.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
