[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
btc_relay = "HY7CpkPjh5FgcU22RmEpqD6T5ZNWSgmwiTDYE5yHRfmf"

[programs.mainnet]
btc_relay = "HY7CpkPjh5FgcU22RmEpqD6T5ZNWSgmwiTDYE5yHRfmf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/artem/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
