[features]
seeds = false
skip-lint = false
[programs.mainnet]
btc_relay = "De2dsY5K3DXBDNzKUjE6KguVP5JUhveKNpMVRmRkazff"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/home/adam/mainnet.key"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
