[workspace]
members = [
    "programs/*"
]

exclude = [
    "block_relayer"
]

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
