[package]
name = "block_relayer"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-client = "0.29.0"
bitcoin = "=0.31.2"
bitcoincore-rpc = "0.19.0"
btc-relay = { path = "../programs/btc-relay" }
electrum-client = { version = "0.19" }
