[package]
name = "block_relayer"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-client = "0.29.0"
bitcoin = "0.32.2"
btc-relay = { path = "../programs/btc-relay" }
electrum-client = { version = "0.19" }
solana-client = "1.18"
solana-sdk = "1.18"
