[package]
name = "block_relayer"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-client = "0.29.0"
base64 = "0.22"
bitcoin = { version = "=0.32.2", default-features = false }
bitcoincore-rpc = "0.19.0"
btc-relay = { path = "../programs/btc-relay" }
env_logger = "0.11"
log = "0.4"
solana-transaction-status = "1.18"
