[relay]
bitcoind_url = "http://localhost:18443"
bitcoin_cookie_file = "/bitcoin/regtest/.cookie"
yona_http = "http://devnet-rpc.yona.network:8899"
yona_ws = "ws://devnet-rpc.yona.network:8900"
yona_keipair = ".config/solana/id.json"
