[package]
name = "btc_faucet"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.7.0"
actix-web = "4.0"
bitcoincore-rpc = "0.19"
chrono = "0.4"
derive_more = "0.99"
env_logger = "0.11"
rusqlite = "0.31"
serde = { version = "1.0", features = ["derive"] }
