name: Anchor

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  anchor:
    runs-on: ubuntu-latest
    container: backpackapp/build:v0.30.1

    steps:
      - uses: actions/checkout@v3
      - name: Install GCC multilib
        run: |
          apt-get update
          apt-get install gcc-multilib -y
      - name: Generate new keypair
        run: solana-keygen new --no-bip39-passphrase -s -o anchor.json
      - name: Check solana config
        run: solana config get
      - name: Install yarn dependencies
        run: yarn install
      - name: Build
        run: anchor build
      - name: Run tests
        run: anchor test