on:
  push:
    branches: [ ci ]
  workflow_dispatch:
    inputs:
      run_step:
        description: 'Do you need to run make a builder image?'
        required: true
        default: 'no'

env:
  CARGO_TERM_COLOR: always
  REGISTRY: registry.digitalocean.com/mov3r-container

jobs:

  make_builder_image:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.run_step == 'yes' }}
    outputs:
      app-image: ${{ steps.build-app-block-relayer-image.outputs.IMAGE }}
      image-tag: ${{ steps.build-app-block-relayer-image.outputs.IMAGE_TAG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200

      - name: Build/push builder image
        run: |
          export IMAGE=$REGISTRY/${GITHUB_REPOSITORY#*/}/builder
          export IMAGE_TAG=$(echo $GITHUB_SHA | head -c7)
          docker build \
            --cache-to=type=inline \
            --cache-from type=registry,ref=$IMAGE:latest \
            -t $IMAGE:latest \
            --target builder \
            --push \
            .
          echo "IMAGE_TAG=$IMAGE_TAG" >> "$GITHUB_OUTPUT"
          echo "IMAGE=$IMAGE" >> "$GITHUB_OUTPUT"

  build:
    runs-on: ubuntu-latest
    outputs:
      app-image: ${{ steps.build-app-block-relayer-image.outputs.IMAGE }}
      image-tag: ${{ steps.build-app-block-relayer-image.outputs.IMAGE_TAG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200

      - name: Build/push block_relayer image
        id: build-app-block-relayer-image
        run: |
          export IMAGE=$REGISTRY/${GITHUB_REPOSITORY#*/}/block-relayer
          export IMAGE_TAG=$(echo $GITHUB_SHA | head -c7)
          docker build \
            --cache-to=type=inline \
            --cache-from type=registry,ref=$REGISTRY/${GITHUB_REPOSITORY#*/}/builder:latest \
            --cache-from type=registry,ref=$IMAGE:latest \
            -t $IMAGE:$IMAGE_TAG \
            -t $IMAGE:latest \
            --target app_block_relayer \
            --push \
            .
          echo "IMAGE_TAG=$IMAGE_TAG" >> "$GITHUB_OUTPUT"
          echo "IMAGE=$IMAGE" >> "$GITHUB_OUTPUT"
